# Generated by Django 6.1.1 on 2026-09-18 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=True, help_text='Публичные альбомы видны всем, приватные — только вам', verbose_name='Публичный')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlbumItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='albums.album', verbose_name='Альбом')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_items', to='posts.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Элемент альбома',
                'verbose_name_plural': 'Элементы альбомов',
                'ordering': ['-added_at'],
                'constraints': [models.UniqueConstraint(fields=('album', 'post'), name='unique_post_per_album')],
            },
        ),
    ]
